function y = doFilterHP(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.6 and DSP System Toolbox 9.8.
% Generated on: 12-Jan-2021 19:06:40

persistent Hd;

if isempty(Hd)
    
    Fstop = 20;     % Stopband Frequency
    Fpass = 30;     % Passband Frequency
    Astop = 60;     % Stopband Attenuation (dB)
    Apass = 0.0001;      % Passband Ripple (dB)
    Fs    = 48000;  % Sampling Frequency
    
    h = fdesign.highpass('fst,fp,ast,ap', Fstop, Fpass, Astop, Apass, Fs);
    
    Hd = design(h, 'butter', ...
        'FilterStructure', 'df2tsos', ...
        'MatchExactly', 'stopband', ...
        'SOSScaleNorm', 'Linf');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);

