function y = doFilter(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.6 and DSP System Toolbox 9.8.
% Generated on: 14-Nov-2020 17:15:40

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    %
    % N    = 4;      % Order
    % F3dB = 7800;   % 3-dB Frequency
    % Fs   = 16000;  % Sampling Frequency
    %
    % h = fdesign.lowpass('n,f3db', N, F3dB, Fs);
    %
    % Hd = design(h, 'butter', ...
    %     'SystemObject', true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 2 1 1 1.9357148371212 0.941700451603727; 1 2 1 1 ...
        1.85907626595821 0.864824898767263], ...
        'ScaleValues', [0.969353822181231; 0.930975291181368; 1]);
end

s = single(x);
y = step(Hd,s);

