% -------------------------------------------------------------------
%  Generated by MATLAB on 17-Nov-2020 16:51:00
%  MATLAB version: 9.6.0.1072779 (R2019a)
% -------------------------------------------------------------------
saveVarsMat = load('matlab.mat');

win = saveVarsMat.win; % <2048x1 double> too many elements

clear saveVarsMat;
